name: Hello World Workflow

on:
  push:
    branches:
      - main  # Le workflow se déclenchera lors d'un push sur la branche "main".
  workflow_dispatch:  # Permet d'exécuter manuellement le workflow depuis GitHub.

jobs:
  say-hello:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Action pour cloner le dépôt.

      - name: Print Hello World
        run: echo "Hello, World!"  # Commande qui affiche "Hello, World!".
