name: Pull or Push Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PUSH_MESSAGE: "C'est un push !"
  PULL_REQUEST_MESSAGE: "C'est une pull request !"

jobs:
  push-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Display push message
        run: echo $PUSH_MESSAGE

  pull-request-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Display pull request message
        run: echo $PULL_REQUEST_MESSAGE
