name: Workflow Liés
on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Envoyer un message depuis le premier job
        run: echo "Premier job exécuté"

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Envoyer un message depuis le second job
        run: echo "Second job exécuté"
